# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json
---
# Final system configuration - services, targets

modules:
  - type: systemd
    system:
      enabled:
        - sshd
        - NetworkManager
        - bluetooth
        - firewalld
        - cockpit.socket
        - gdm
        - tuned
        - acpid
      disabled:
        - kdump

  - type: script
    scripts:
      - set-graphical-target.sh
